const ui={en:{live:"LIVE PRODUCT EXPERIENCE",choose:"CHOOSE A SCENARIO",title:"See an intelligent space think and act.",subtitle:"Select a real workplace task, then watch Office Claw coordinate people, devices and services.",auto:"AUTO DEMO",autoOff:"OFF",autoOn:"ON",systemOnline:"SYSTEM ONLINE",tryCommand:"TRY A COMMAND",run:"RUN",sense:"SENSE",senseSub:"Space + context",understand:"UNDERSTAND",understandSub:"Intent + permission",coordinate:"COORDINATE",coordinateSub:"Agents + skills",act:"ACT",actSub:"Devices + services",activity:"LIVE ACTIVITY",outcome:"BUSINESS OUTCOME",ready:"READY",running:"RUNNING",complete:"COMPLETE",architecture:"OFFICE CLAW · MULTI-AGENT SPATIAL INTELLIGENCE",privacy:"LOCAL-FIRST · PERMISSION-AWARE · BRAND-AGNOSTIC",pilot:"DISCUSS A PILOT"},zh:{live:"实时产品体验",choose:"选择一个场景",title:"看懂一个智能空间如何思考与行动",subtitle:"选择真实办公任务，观看 Office Claw 协同人员、设备与服务。",auto:"自动演示",autoOff:"关闭",autoOn:"开启",systemOnline:"系统在线",tryCommand:"试着说一句",run:"执行",sense:"感知",senseSub:"空间与情境",understand:"理解",understandSub:"意图与权限",coordinate:"协同",coordinateSub:"智能体与技能",act:"执行",actSub:"设备与服务",activity:"实时执行记录",outcome:"业务结果",ready:"就绪",running:"执行中",complete:"已完成",architecture:"OFFICE CLAW · 多智能体空间智能",privacy:"本地优先 · 权限可控 · 兼容多品牌",pilot:"预约试点"},th:{live:"ประสบการณ์ผลิตภัณฑ์แบบสด",choose:"เลือกสถานการณ์",title:"ดูพื้นที่อัจฉริยะคิดและลงมือทำ",subtitle:"เลือกงานจริง แล้วดู Office Claw ประสานคน อุปกรณ์ และบริการ",auto:"สาธิตอัตโนมัติ",autoOff:"ปิด",autoOn:"เปิด",systemOnline:"ระบบออนไลน์",tryCommand:"ลองออกคำสั่ง",run:"เริ่ม",sense:"รับรู้",senseSub:"พื้นที่และบริบท",understand:"เข้าใจ",understandSub:"เจตนาและสิทธิ์",coordinate:"ประสานงาน",coordinateSub:"เอเจนต์และทักษะ",act:"ลงมือทำ",actSub:"อุปกรณ์และบริการ",activity:"กิจกรรมแบบสด",outcome:"ผลลัพธ์ทางธุรกิจ",ready:"พร้อม",running:"กำลังทำงาน",complete:"เสร็จสิ้น",architecture:"OFFICE CLAW · ระบบอัจฉริยะแบบหลายเอเจนต์",privacy:"ประมวลผลในพื้นที่ · ควบคุมสิทธิ์ · รองรับหลายแบรนด์",pilot:"หารือโครงการนำร่อง"}};

const scenes={en:[
{icon:"01",name:"Visitor arrival",tag:"RECEPTION",title:"A welcome that runs itself.",description:"From invitation and identity verification to access and wayfinding, every arrival is coordinated automatically.",command:"Welcome Somchai from ABC Property and guide him to Meeting Room 3.",metric:"< 20 sec",metricLabel:"visitor check-in",outcome:"Less waiting, less front-desk work and a consistent arrival experience.",image:"./demo-space.png",logs:["Invitation and visitor identity matched","Access permission issued for the visit window","Meeting host and room status confirmed","Route sent and reception screen updated"]},
{icon:"02",name:"One-click meeting",tag:"MEETING",title:"One sentence. A ready room.",description:"Office Claw finds the right room, coordinates attendees and prepares the physical environment.",command:"Book a 10-person meeting tomorrow at 2 PM with a screen.",metric:"7 → 1",metricLabel:"steps reduced",outcome:"Booking, access, equipment, lighting and climate are completed in one flow.",image:"./demo-space.png",logs:["Calendar availability and room capacity checked","Room 6B-12 selected and attendees notified","Access window and equipment profile created","Lighting, HVAC and display scheduled"]},
{icon:"03",name:"Energy optimization",tag:"ENERGY",title:"Comfort where needed. Savings everywhere.",description:"Occupancy, weather and equipment data continuously shape lighting and HVAC decisions.",command:"Reduce energy use on the third floor without affecting occupied rooms.",metric:"-30%",metricLabel:"target energy use",outcome:"Dynamic control reduces waste while keeping occupied spaces comfortable.",image:"./demo-iot.png",logs:["Occupancy and indoor comfort signals analyzed","Unused zones and abnormal loads identified","HVAC setpoints and lighting zones optimized","Comfort thresholds retained and savings tracked"]},
{icon:"04",name:"Maintenance dispatch",tag:"OPERATIONS",title:"Report naturally. Resolve automatically.",description:"A spoken fault becomes a structured work order with diagnosis, dispatch and closure tracking.",command:"The corridor light on level 3 is broken. Please arrange a repair.",metric:"24H",metricLabel:"service response",outcome:"Fewer phone calls, clearer accountability and a complete maintenance record.",image:"./demo-iot.png",logs:["Location and equipment matched to asset record","Fault category and service priority determined","Qualified technician selected and dispatched","Work order created with verification checkpoint"]},
{icon:"05",name:"Enterprise services",tag:"SKILLS",title:"Bring business services into the space.",description:"Legal, recruitment and finance skills become available where employees already work.",command:"Review this lease clause and flag the main risks for our team.",metric:"1 → many",metricLabel:"skills on demand",outcome:"Specialist workflows become easier to access without adding a large internal team.",image:"./demo-space.png",logs:["Document type and requested outcome recognized","Tenant permissions and data boundary verified","Legal review skill invoked with local context","Risk summary and recommended actions prepared"]},
{icon:"06",name:"Operations intelligence",tag:"INSIGHT",title:"Turn space data into decisions.",description:"Occupancy, energy, assets and service data become alerts, forecasts and operating recommendations.",command:"Show me this week's underused areas and the biggest operating opportunity.",metric:"6.2×",metricLabel:"daily seat turnover",outcome:"Operators see what is happening, why it matters and what to do next.",image:"./demo-iot.png",logs:["Occupancy, booking and access data consolidated","Underused zones and peak-time pressure detected","Energy and service cost drivers compared","Recommended layout and operating actions generated"]}
],zh:[
{icon:"01",name:"智能访客接待",tag:"接待",title:"让每一次到访自动有序",description:"从邀请、身份核验到门禁与路线引导，系统自动协调整个到访过程。",command:"接待来自 ABC Property 的 Somchai，并引导他到3号会议室。",metric:"< 20秒",metricLabel:"完成访客签到",outcome:"减少等待和前台工作，让每位访客获得一致、专业的体验。",image:"./demo-space.png",logs:["已匹配访客邀请与身份信息","已生成本次到访的门禁权限","已确认接待人及会议室状态","已发送路线并更新前台屏幕"]},
{icon:"02",name:"一句话开会",tag:"会议",title:"说一句，会议室就绪",description:"Office Claw 自动寻找合适会议室、协调参会人，并准备现场环境。",command:"预约明天下午2点、10个人、有投影的会议室。",metric:"7 → 1",metricLabel:"操作步骤",outcome:"预约、通知、门禁、设备、灯光和空调在一个流程内完成。",image:"./demo-space.png",logs:["已检查日程、容量和会议需求","已选择6B-12会议室并通知参会人","已生成门禁时段与设备配置","已预约灯光、空调与显示设备"]},
{icon:"03",name:"能源智能优化",tag:"节能",title:"有人时舒适，无人时节能",description:"根据人员、天气和设备数据，持续优化照明与空调策略。",command:"降低三层能耗，但不要影响正在使用的房间。",metric:"-30%",metricLabel:"目标能源消耗",outcome:"在保持办公舒适度的同时，动态减少空置区域的能源浪费。",image:"./demo-iot.png",logs:["已分析人员分布与室内舒适度","已识别空置区域和异常能耗","已优化空调设定与照明分区","已保留舒适阈值并跟踪节能效果"]},
{icon:"04",name:"智能报修派单",tag:"运营",title:"自然报修，自动闭环",description:"一句自然语言描述即可生成结构化工单，完成诊断、派单与验收。",command:"三楼走廊的灯坏了，请安排维修。",metric:"24小时",metricLabel:"服务响应",outcome:"减少电话沟通，明确责任，并沉淀完整的设施维护记录。",image:"./demo-iot.png",logs:["已匹配位置、设备与资产档案","已判断故障类型与服务优先级","已选择合适维修人员并派单","已创建工单与完工验收节点"]},
{icon:"05",name:"企业专业服务",tag:"技能",title:"把企业服务带进办公空间",description:"法务、招聘、财务等专业能力，在员工工作的地方随时调用。",command:"审查这份租赁合同条款，并提示主要风险。",metric:"1 → 多项",metricLabel:"按需调用专业技能",outcome:"无需扩充庞大团队，也能更便捷地使用标准化专业服务。",image:"./demo-space.png",logs:["已识别文档类型与任务目标","已验证租户权限与数据边界","已结合本地背景调用法务技能","已生成风险摘要与行动建议"]},
{icon:"06",name:"运营数据洞察",tag:"洞察",title:"让空间数据成为决策",description:"将客流、能耗、资产和服务数据转化为预警、预测与行动建议。",command:"找出本周利用率偏低的区域和最大的运营机会。",metric:"6.2次",metricLabel:"日均座位周转",outcome:"运营者不仅看见发生了什么，还能理解原因并获得下一步建议。",image:"./demo-iot.png",logs:["已汇总客流、预约与门禁数据","已识别低利用区域与高峰压力","已对比能源和服务成本驱动因素","已生成布局与运营优化建议"]}
],th:[
{icon:"01",name:"ต้อนรับผู้มาเยือน",tag:"ต้อนรับ",title:"การต้อนรับที่ดำเนินการได้เอง",description:"ตั้งแต่คำเชิญ ยืนยันตัวตน การเข้าถึง จนถึงการนำทาง ทุกขั้นตอนประสานงานอัตโนมัติ",command:"ต้อนรับคุณสมชายจาก ABC Property และนำทางไปห้องประชุม 3",metric:"< 20 วินาที",metricLabel:"เช็กอินผู้มาเยือน",outcome:"ลดเวลารอ ลดภาระพนักงานต้อนรับ และสร้างประสบการณ์ที่เป็นมาตรฐาน",image:"./demo-space.png",logs:["จับคู่คำเชิญและข้อมูลประจำตัวแล้ว","ออกสิทธิ์เข้าใช้งานตามช่วงเวลาแล้ว","ยืนยันเจ้าภาพและสถานะห้องแล้ว","ส่งเส้นทางและอัปเดตหน้าจอต้อนรับแล้ว"]},
{icon:"02",name:"ประชุมในคลิกเดียว",tag:"ประชุม",title:"พูดครั้งเดียว ห้องก็พร้อม",description:"Office Claw เลือกห้อง ประสานผู้เข้าร่วม และเตรียมสภาพแวดล้อมให้พร้อม",command:"จองห้องประชุม 10 คน พรุ่งนี้บ่ายสอง พร้อมจอแสดงผล",metric:"7 → 1",metricLabel:"ลดขั้นตอน",outcome:"การจอง การเข้าถึง อุปกรณ์ แสง และอากาศเสร็จในขั้นตอนเดียว",image:"./demo-space.png",logs:["ตรวจสอบปฏิทิน ความจุ และความต้องการแล้ว","เลือกห้อง 6B-12 และแจ้งผู้เข้าร่วมแล้ว","สร้างช่วงเวลาการเข้าถึงและโปรไฟล์อุปกรณ์แล้ว","ตั้งเวลาแสง แอร์ และจอแสดงผลแล้ว"]},
{icon:"03",name:"เพิ่มประสิทธิภาพพลังงาน",tag:"พลังงาน",title:"สบายเมื่อใช้งาน ประหยัดเมื่อว่าง",description:"ข้อมูลการใช้งาน อากาศ และอุปกรณ์ช่วยปรับแสงและแอร์อย่างต่อเนื่อง",command:"ลดพลังงานชั้น 3 โดยไม่กระทบห้องที่กำลังใช้งาน",metric:"-30%",metricLabel:"เป้าหมายพลังงาน",outcome:"ลดการสูญเสียพลังงานโดยยังคงความสบายในพื้นที่ใช้งาน",image:"./demo-iot.png",logs:["วิเคราะห์การใช้งานและความสบายแล้ว","ระบุพื้นที่ว่างและโหลดผิดปกติแล้ว","ปรับค่าแอร์และโซนแสงแล้ว","รักษาระดับความสบายและติดตามผลแล้ว"]},
{icon:"04",name:"แจ้งซ่อมอัตโนมัติ",tag:"ปฏิบัติการ",title:"แจ้งอย่างเป็นธรรมชาติ แก้ไขอัตโนมัติ",description:"คำพูดหนึ่งประโยคกลายเป็นใบงานที่มีการวินิจฉัย มอบหมาย และติดตามผล",command:"ไฟทางเดินชั้น 3 เสีย กรุณาจัดช่างซ่อม",metric:"24 ชม.",metricLabel:"การตอบสนอง",outcome:"ลดการโทรศัพท์ เพิ่มความรับผิดชอบ และมีประวัติการซ่อมครบถ้วน",image:"./demo-iot.png",logs:["จับคู่ตำแหน่งและอุปกรณ์กับทะเบียนทรัพย์สินแล้ว","กำหนดประเภทปัญหาและลำดับความสำคัญแล้ว","เลือกและมอบหมายช่างที่เหมาะสมแล้ว","สร้างใบงานพร้อมจุดตรวจรับแล้ว"]},
{icon:"05",name:"บริการระดับองค์กร",tag:"ทักษะ",title:"นำบริการธุรกิจเข้ามาในพื้นที่",description:"กฎหมาย สรรหา และการเงิน พร้อมใช้งานในสถานที่ที่พนักงานทำงาน",command:"ตรวจสอบข้อสัญญาเช่านี้และระบุความเสี่ยงหลัก",metric:"1 → หลาย",metricLabel:"ทักษะตามต้องการ",outcome:"เข้าถึงกระบวนการผู้เชี่ยวชาญโดยไม่ต้องเพิ่มทีมขนาดใหญ่",image:"./demo-space.png",logs:["ระบุประเภทเอกสารและผลลัพธ์ที่ต้องการแล้ว","ตรวจสอบสิทธิ์และขอบเขตข้อมูลแล้ว","เรียกใช้ทักษะกฎหมายพร้อมบริบทภายในแล้ว","จัดทำสรุปความเสี่ยงและข้อเสนอแนะแล้ว"]},
{icon:"06",name:"ข้อมูลเชิงลึกการดำเนินงาน",tag:"ข้อมูล",title:"เปลี่ยนข้อมูลพื้นที่เป็นการตัดสินใจ",description:"ข้อมูลการใช้งาน พลังงาน ทรัพย์สิน และบริการ กลายเป็นคำเตือนและคำแนะนำ",command:"แสดงพื้นที่ใช้งานต่ำและโอกาสสำคัญที่สุดของสัปดาห์นี้",metric:"6.2×",metricLabel:"การหมุนเวียนที่นั่งต่อวัน",outcome:"ผู้ดูแลเห็นสิ่งที่เกิดขึ้น เหตุผล และสิ่งที่ควรทำต่อไป",image:"./demo-iot.png",logs:["รวมข้อมูลการใช้งาน การจอง และการเข้าถึงแล้ว","ตรวจพบพื้นที่ใช้งานต่ำและช่วงเวลาหนาแน่นแล้ว","เปรียบเทียบปัจจัยต้นทุนพลังงานและบริการแล้ว","สร้างข้อเสนอแนะด้านผังและการดำเนินงานแล้ว"]}
]};

let lang=(new URLSearchParams(location.search).get("lang")||localStorage.getItem("ai-office-demo-lang")||(/zh/i.test(navigator.language)?"zh":/th/i.test(navigator.language)?"th":"en"));
if(!ui[lang])lang="en";let current=Math.max(0,Math.min(5,Number(new URLSearchParams(location.search).get("scene"))||0)),running=false,auto=false,autoTimer;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function setLanguage(next){lang=next;localStorage.setItem("ai-office-demo-lang",lang);document.documentElement.lang=lang;document.title=lang==="zh"?"AI OFFICE 产品交互体验":lang==="th"?"ประสบการณ์ AI OFFICE":"AI OFFICE Live Experience";$$('[data-i18n]').forEach(el=>{const value=ui[lang][el.dataset.i18n];if(value)el.textContent=value});$$('[data-lang]').forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));$("#contactLink").href=lang==="zh"?"./zh.html#contact":lang==="th"?"./th.html#contact":"./index.html#contact";renderList();selectScene(current)}
function renderList(){const list=$("#scenarioList");list.innerHTML="";scenes[lang].forEach((s,i)=>{const b=document.createElement("button");b.type="button";b.className="scenario-button"+(i===current?" active":"");b.innerHTML=`<span>${s.icon}</span><b>${s.name}</b><small>${s.tag}</small><i></i>`;b.addEventListener("click",()=>{stopRun();selectScene(i)});list.appendChild(b)})}
function selectScene(i){current=(i+6)%6;const s=scenes[lang][current];$("#sceneIndex").textContent=`${String(current+1).padStart(2,"0")} / 06`;$("#sceneTitle").textContent=s.title;$("#sceneDescription").textContent=s.description;$("#commandInput").value=s.command;$("#metricValue").textContent=s.metric;$("#metricLabel").textContent=s.metricLabel;$("#sceneOutcome").textContent=s.outcome;$("#sceneImage").src=s.image;$("#activityLog").innerHTML="";$("#runState").textContent=ui[lang].ready;$("#runState").className="";resetPipeline();renderList()}
function resetPipeline(){$$(".pipeline-step").forEach(x=>x.classList.remove("active","done"));$$('.pipeline-line').forEach(x=>x.classList.remove("done"))}
function stopRun(){running=false}
async function runScene(){if(running)return;running=true;resetPipeline();$("#activityLog").innerHTML="";$("#runState").textContent=ui[lang].running;$("#runState").className="running";const s=scenes[lang][current];for(let i=0;i<4&&running;i++){const step=$$(".pipeline-step")[i];step.classList.add("active");await wait(420);step.classList.remove("active");step.classList.add("done");if(i<3)$$(".pipeline-line")[i].classList.add("done");addLog(s.logs[i],i);await wait(360)}if(running){$("#runState").textContent=ui[lang].complete;$("#runState").className=""}running=false}
function addLog(text,i){const row=document.createElement("div");row.className="log-line done";const now=new Date();row.innerHTML=`<time>${now.toLocaleTimeString([], {hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><i></i><span>${text}</span>`;row.style.animationDelay=`${i*.04}s`;$("#activityLog").appendChild(row)}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function toggleAuto(){auto=!auto;$(".auto-control").classList.toggle("on",auto);$("#autoStatus").textContent=auto?ui[lang].autoOn:ui[lang].autoOff;clearInterval(autoTimer);if(auto){runScene();autoTimer=setInterval(()=>{selectScene(current+1);runScene()},9000)}}
$$('[data-lang]').forEach(b=>b.addEventListener("click",()=>setLanguage(b.dataset.lang)));$("#runButton").addEventListener("click",runScene);$("#commandInput").addEventListener("keydown",e=>{if(e.key==="Enter")runScene()});$("#autoButton").addEventListener("click",toggleAuto);$("#fullscreenButton").addEventListener("click",()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()});setLanguage(lang);setTimeout(runScene,600);
